name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub Pages 배포에 필요한 권한

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false # 아직 install 하지 않음

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install  # 의존성 설치 확실히 하기

      - name: Build
        run: |
          pnpm build
        env:
          CI: false
          NODE_ENV: production

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll # Jekyll 처리 방지

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
